import type { PlotRendererLanguage, ScientificChartType } from '../shared/scientificPlot';
import { getRendererCapability, SCIENTIFIC_CHART_TYPES } from '../shared/scientificPlot';

export interface GeneratedPlotScript {
  language: Exclude<PlotRendererLanguage, 'javascript'>;
  fileName: string;
  content: string;
  previewFormats: Array<'svg' | 'png' | 'html'>;
  supportedChartTypes: ScientificChartType[];
}

export function compilePlotScript(
  language: Exclude<PlotRendererLanguage, 'javascript'>
): GeneratedPlotScript {
  const supportedChartTypes = SCIENTIFIC_CHART_TYPES.filter(
    (chartType) => getRendererCapability(language, chartType).supported
  );
  if (language === 'python') {
    return { language, fileName: 'render_plot.py', content: PYTHON_SCRIPT, previewFormats: ['svg', 'png', 'html'], supportedChartTypes };
  }
  if (language === 'r') {
    return { language, fileName: 'render_plot.R', content: R_SCRIPT, previewFormats: ['svg', 'png', 'html'], supportedChartTypes };
  }
  return { language, fileName: 'render_plot.m', content: MATLAB_SCRIPT, previewFormats: ['png', 'svg'], supportedChartTypes };
}

export function assertGeneratedPlotScript(script: GeneratedPlotScript): true {
  if (!script.content.includes('plot-spec.json') || !script.content.includes('data.csv')) {
    throw new Error('Generated plot script must read the controlled spec and data files.');
  }
  if (script.content.length > 250_000) throw new Error('Generated plot script is unexpectedly large.');
  if (/child_process|subprocess\.|os\.system|system\(|shell\s*=\s*true/i.test(script.content)) {
    throw new Error('Generated plot script contains a forbidden process-execution primitive.');
  }
  return true;
}

const PYTHON_SCRIPT = String.raw`# Generated by FTranslate Scientific Plotting Studio.
# This file reads only plot-spec.json and data.csv from its working directory.
import json, math, os, sys, warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import ticker
import seaborn as sns
from scipy import stats

ROOT = Path.cwd()
SPEC = json.loads((ROOT / 'plot-spec.json').read_text(encoding='utf-8'))
DATA = pd.read_csv(ROOT / 'data.csv')
OUT = ROOT / 'output'
OUT.mkdir(exist_ok=True)
chart = SPEC['chart']['type']
enc = SPEC.get('encodings', {})
theme = SPEC.get('theme', {})
palette = theme.get('palette', ['#526f8a','#738c7a','#87768f'])
sns.set_theme(style='whitegrid' if theme.get('grid', True) else 'white', palette=palette)
plt.rcParams.update({'font.family': theme.get('fontFamily','Arial').split(',')[0], 'font.size': theme.get('baseFontSize',10)})
fig = plt.figure(figsize=(max(3, theme.get('canvas',{}).get('widthMm',180)/25.4), max(2.4, theme.get('canvas',{}).get('heightMm',120)/25.4)))
ax = fig.add_subplot(111, projection='3d' if chart in ('scatter3d','surface3d') else None)
x, y = enc.get('x'), enc.get('y')
hue = enc.get('color') or enc.get('group')
plotly_figure = None

def axis_spec(axis_id):
    return next((item for item in SPEC.get('axes', []) if item.get('id') == axis_id), {})

def axis_formatter(axis):
    mode=axis.get('numberFormat','auto'); places=int(axis.get('decimalPlaces',2)); prefix=axis.get('prefix',''); suffix=axis.get('suffix','')
    def render(value, _position=None):
        if mode=='scientific': text=f'{value:.{places}e}'
        elif mode=='percent': text=f'{value*100:.{places}f}%'
        elif mode=='fixed': text=f'{value:,.{places}f}' if axis.get('thousandsSeparator',True) else f'{value:.{places}f}'
        else: text=f'{value:g}'
        return f'{prefix}{text}{suffix}'
    return ticker.FuncFormatter(render)

def apply_axis(axis_id):
    axis=axis_spec(axis_id); obj=ax.xaxis if axis_id=='x' else ax.yaxis
    if axis.get('visible',True) is False: obj.set_visible(False); return
    scale=axis.get('scale','auto')
    if scale=='log':
        (ax.set_xscale if axis_id=='x' else ax.set_yscale)('log',base=axis.get('logBase',10))
    elif scale=='linear': (ax.set_xscale if axis_id=='x' else ax.set_yscale)('linear')
    minimum,maximum=axis.get('min'),axis.get('max')
    if minimum is not None or maximum is not None:
        current=(ax.get_xlim if axis_id=='x' else ax.get_ylim)(); (ax.set_xlim if axis_id=='x' else ax.set_ylim)(minimum if minimum is not None else current[0],maximum if maximum is not None else current[1])
    if axis.get('reverse',False): (ax.invert_xaxis if axis_id=='x' else ax.invert_yaxis)()
    if axis.get('position')=='secondary':
        (obj.tick_top if axis_id=='x' else obj.tick_right)(); (obj.set_label_position)('top' if axis_id=='x' else 'right')
    obj.set_visible(axis.get('showLine',True) or axis.get('showTicks',True) or axis.get('showLabels',True))
    tick_options={'axis':axis_id,'labelsize':axis.get('labelFontSize',theme.get('baseFontSize',10)),'labelrotation':axis.get('labelRotation',0),'labelcolor':axis.get('labelColor','#526172')}
    if axis_id=='x': tick_options.update({'bottom':axis.get('showTicks',True),'labelbottom':axis.get('showLabels',True)})
    else: tick_options.update({'left':axis.get('showTicks',True),'labelleft':axis.get('showLabels',True)})
    ax.tick_params(**tick_options)
    if axis.get('tickInterval'):
        obj.set_major_locator(ticker.MultipleLocator(axis['tickInterval']))
    elif axis.get('tickCount'):
        obj.set_major_locator(ticker.MaxNLocator(int(axis['tickCount'])))
    if axis.get('minorTicks',False): obj.set_minor_locator(ticker.AutoMinorLocator())
    if axis.get('numberFormat','auto')!='auto' or axis.get('prefix') or axis.get('suffix'): obj.set_major_formatter(axis_formatter(axis))
    ax.grid(axis.get('showGrid',theme.get('grid',True)),axis=axis_id,which='major',color=axis.get('gridColor','#e4e8ed'),linewidth=axis.get('gridWidth',.8))
    if axis.get('showMinorGrid',False): ax.grid(True,axis=axis_id,which='minor',color=axis.get('gridColor','#eef1f4'),linewidth=max(.1,axis.get('gridWidth',.8)*.6),alpha=.7)
    label=axis.get('label')
    if label:
        setter=ax.set_xlabel if axis_id=='x' else ax.set_ylabel; setter(label,labelpad=axis.get('titleGap',30 if axis_id=='x' else 42),fontsize=axis.get('titleFontSize',theme.get('baseFontSize',10)),color=axis.get('titleColor','#26364a'))

if chart in ('line','area'):
    sns.lineplot(data=DATA, x=x, y=y, hue=hue, marker='o' if SPEC['chart'].get('showPoints',True) else None, ax=ax)
    if chart == 'area' and not hue:
        ax.fill_between(DATA[x], DATA[y], alpha=.2)
elif chart == 'scatter':
    sns.scatterplot(data=DATA, x=x, y=y, hue=hue, size=enc.get('size'), ax=ax)
elif chart == 'bar':
    sns.barplot(data=DATA, x=x, y=y, hue=hue, ax=ax, errorbar=None)
elif chart == 'histogram':
    sns.histplot(data=DATA, x=x or y, hue=hue, kde=False, ax=ax)
elif chart == 'density':
    sns.kdeplot(data=DATA, x=x or y, hue=hue, fill=False, ax=ax)
elif chart == 'ecdf':
    sns.ecdfplot(data=DATA, x=x or y, hue=hue, ax=ax)
elif chart in ('box','violin','raincloud','beeswarm'):
    if chart == 'box': sns.boxplot(data=DATA, x=x, y=y, hue=hue if hue != x else None, ax=ax)
    elif chart == 'violin': sns.violinplot(data=DATA, x=x, y=y, hue=hue if hue != x else None, inner='box', ax=ax)
    elif chart == 'beeswarm': sns.swarmplot(data=DATA, x=x, y=y, hue=hue if hue != x else None, ax=ax)
    else:
        sns.violinplot(data=DATA, x=x, y=y, hue=hue if hue != x else None, inner=None, cut=0, alpha=.35, ax=ax)
        sns.boxplot(data=DATA, x=x, y=y, hue=hue if hue != x else None, width=.18, showfliers=False, ax=ax)
        sns.stripplot(data=DATA, x=x, y=y, hue=None, color='#26364a', alpha=.45, size=3, ax=ax)
elif chart in ('heatmap','correlation','clusteredHeatmap'):
    if chart == 'correlation': matrix = DATA.select_dtypes(include=np.number).corr()
    elif chart == 'clusteredHeatmap':
        matrix = DATA.select_dtypes(include=np.number).corr()
        grid = sns.clustermap(matrix, cmap='vlag', center=0)
        grid.savefig(OUT/'preview.svg'); grid.savefig(OUT/'preview.png', dpi=180); plt.close('all'); fig = None
    else: matrix = DATA.pivot_table(index=y, columns=x, values=enc.get('value') or enc.get('color'), aggfunc='mean')
    if fig is not None: sns.heatmap(matrix, cmap='viridis', ax=ax)
elif chart in ('contour','density2d'):
    if enc.get('value'):
        pivot=DATA.pivot_table(index=y,columns=x,values=enc['value'],aggfunc='mean'); X,Y=np.meshgrid(pivot.columns.astype(float),pivot.index.astype(float)); Z=pivot.values
        ax.contourf(X,Y,Z,levels=12,cmap='viridis'); ax.contour(X,Y,Z,levels=12,colors='k',linewidths=.35)
    else: sns.kdeplot(data=DATA,x=x,y=y,fill=chart=='density2d',levels=12,cmap='viridis',ax=ax)
elif chart in ('scatter3d','surface3d'):
    z=enc.get('value') or enc.get('size') or enc.get('color')
    if chart == 'scatter3d': ax.scatter(DATA[x],DATA[y],DATA[z],c=DATA[z],cmap='viridis')
    else: ax.plot_trisurf(DATA[x],DATA[y],DATA[z],cmap='viridis',linewidth=.1)
    ax.set_zlabel(z)
elif chart in ('sankey','alluvial'):
    import plotly.graph_objects as go
    source,target,value=enc['source'],enc['target'],enc.get('value')
    labels=pd.unique(pd.concat([DATA[source].astype(str),DATA[target].astype(str)])).tolist(); idx={v:i for i,v in enumerate(labels)}
    plotly_figure=go.Figure(go.Sankey(node={'label':labels},link={'source':[idx[v] for v in DATA[source].astype(str)],'target':[idx[v] for v in DATA[target].astype(str)],'value':DATA[value].astype(float).tolist() if value else [1]*len(DATA)}))
elif chart == 'survival':
    for name,group in DATA.groupby(hue) if hue else [('Survival',DATA)]: ax.step(group[x],group[y],where='post',label=name)
    if hue: ax.legend()
elif chart == 'forest':
    low,high=enc['errorLower'],enc['errorUpper']; positions=np.arange(len(DATA)); ax.errorbar(DATA[x],positions,xerr=[DATA[x]-DATA[low],DATA[high]-DATA[x]],fmt='o'); ax.set_yticks(positions,DATA[y]); ax.axvline(0,color='#777',lw=.8)
elif chart == 'volcano':
    p=np.maximum(DATA[y].astype(float),np.finfo(float).tiny); fold=DATA[x].astype(float); sig=(p<.05)&(np.abs(fold)>=1)
    ax.scatter(fold[~sig],-np.log10(p[~sig]),s=12,c='#aab2bb'); ax.scatter(fold[sig],-np.log10(p[sig]),s=15,c=np.where(fold[sig]>0,'#9b544e','#3f6685'))
elif chart == 'radar':
    numeric=DATA.select_dtypes(include=np.number); labels=numeric.columns.tolist(); values=numeric.iloc[0].tolist(); angles=np.linspace(0,2*np.pi,len(labels),endpoint=False).tolist(); values+=values[:1]; angles+=angles[:1]
    plt.close(fig); fig=plt.figure(); ax=fig.add_subplot(111,polar=True); ax.plot(angles,values); ax.fill(angles,values,alpha=.15); ax.set_thetagrids(np.degrees(angles[:-1]),labels)
else: raise ValueError(f'Unsupported controlled chart type: {chart}')

if plotly_figure is not None:
    plotly_figure.update_layout(title=SPEC['chart'].get('title') or SPEC.get('title'))
    plotly_figure.write_html(OUT/'preview.html', include_plotlyjs=True, full_html=True)
    preview='preview.html'
elif fig is not None:
    ax.set_title(SPEC['chart'].get('title') or SPEC.get('title',''))
    if x and chart not in ('radar',): ax.set_xlabel(SPEC.get('axes',[{},{}])[0].get('label') or x)
    if y and chart not in ('forest','radar'): ax.set_ylabel(next((a.get('label') for a in SPEC.get('axes',[]) if a.get('id')=='y'),None) or y)
    if chart not in ('radar',): apply_axis('x'); apply_axis('y')
    fig.tight_layout(); fig.savefig(OUT/'preview.svg',bbox_inches='tight'); fig.savefig(OUT/'preview.png',dpi=180,bbox_inches='tight'); preview='preview.svg'
    for preset in SPEC.get('exports',[]):
        fmt=preset.get('format'); dpi=preset.get('dpi',300)
        if fmt in ('png','svg','pdf','tiff'): fig.savefig(OUT/f"export-{preset.get('id','figure')}.{fmt}",dpi=dpi,bbox_inches='tight',transparent=preset.get('transparent',False))

results=[]
for analysis in SPEC.get('analysis',[]):
    if not analysis.get('enabled',True): continue
    values=pd.to_numeric(DATA[analysis['valueField']],errors='coerce').dropna()
    item={'analysisId':analysis['id'],'method':analysis['type'],'engine':'python/scipy','n':int(len(values))}
    if analysis['type']=='descriptive' and len(values)>1: item.update({'mean':float(values.mean()),'sd':float(values.std(ddof=1))})
    elif analysis.get('groupField') and len(analysis.get('groups',[]))>=2:
        a=values[DATA[analysis['groupField']]==analysis['groups'][0]]; b=values[DATA[analysis['groupField']]==analysis['groups'][1]]
        if analysis['type']=='independentT': item.update(dict(zip(('statistic','pValue'),map(float,stats.ttest_ind(a,b,equal_var=False,nan_policy='omit')))))
    results.append(item)
(OUT/'analysis-results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2),encoding='utf-8')
(OUT/'render-manifest.json').write_text(json.dumps({'language':'python','chartType':chart,'preview':preview,'versions':{'python':sys.version.split()[0],'pandas':pd.__version__,'matplotlib':matplotlib.__version__}},indent=2),encoding='utf-8')
`;

const R_SCRIPT = String.raw`# Generated by FTranslate Scientific Plotting Studio.
suppressPackageStartupMessages({library(jsonlite);library(ggplot2)})
or_default <- function(x,y) if(is.null(x)) y else x
spec <- fromJSON('plot-spec.json', simplifyVector=FALSE)
data <- read.csv('data.csv', check.names=FALSE, stringsAsFactors=FALSE)
dir.create('output', showWarnings=FALSE)
chart <- spec$chart$type; enc <- spec$encodings
x <- enc$x; y <- enc$y; group <- if(!is.null(enc$color)) enc$color else enc$group
aes_base <- aes(x=.data[[x]], y=.data[[y]])
axis_by_id <- function(id) { hits <- Filter(function(item) identical(item$id,id),spec$axes); if(length(hits)) hits[[1]] else list(id=id,scale='auto') }
axis_labels <- function(axis) function(values) { places <- or_default(axis$decimalPlaces,2); mode <- or_default(axis$numberFormat,'auto'); rendered <- if(mode=='scientific') formatC(values,format='e',digits=places) else if(mode=='percent') paste0(formatC(values*100,format='f',digits=places),'%') else if(mode=='fixed') formatC(values,format='f',digits=places,big.mark=if(isFALSE(axis$thousandsSeparator)) '' else ',') else as.character(values); paste0(or_default(axis$prefix,''),rendered,or_default(axis$suffix,'')) }
axis_breaks <- function(axis) { if(is.null(axis$tickInterval)) waiver() else function(limits) seq(ceiling(limits[1]/axis$tickInterval)*axis$tickInterval,floor(limits[2]/axis$tickInterval)*axis$tickInterval,by=axis$tickInterval) }
axis_limits <- function(axis) if(is.null(axis$min)&&is.null(axis$max)) NULL else c(or_default(axis$min,NA),or_default(axis$max,NA))
p <- NULL
if(chart %in% c('line','area')) {
  p <- ggplot(data,aes_base)+geom_line(aes(color=if(!is.null(group)) .data[[group]] else NULL,group=if(!is.null(group)) .data[[group]] else 1),linewidth=spec$theme$lineWidth)+geom_point(size=spec$theme$markerSize/2)
} else if(chart=='scatter') {
  p <- ggplot(data,aes_base)+geom_point(aes(color=if(!is.null(group)) .data[[group]] else NULL),size=spec$theme$markerSize/2)
} else if(chart=='bar') {
  p <- ggplot(data,aes_base)+geom_col(aes(fill=if(!is.null(group)) .data[[group]] else NULL),position=if(isTRUE(spec$chart$stacked)) 'stack' else 'dodge')
} else if(chart=='histogram') {
  p <- ggplot(data,aes(x=.data[[if(!is.null(x)) x else y]],fill=if(!is.null(group)) .data[[group]] else NULL))+geom_histogram(bins=30,alpha=.7,position='identity')
} else if(chart=='density') {
  p <- ggplot(data,aes(x=.data[[if(!is.null(x)) x else y]],color=if(!is.null(group)) .data[[group]] else NULL))+geom_density()
} else if(chart=='ecdf') {
  p <- ggplot(data,aes(x=.data[[if(!is.null(x)) x else y]],color=if(!is.null(group)) .data[[group]] else NULL))+stat_ecdf()
} else if(chart=='box') {
  p <- ggplot(data,aes_base)+geom_boxplot(aes(fill=if(!is.null(group)) .data[[group]] else NULL))
} else if(chart %in% c('violin','raincloud')) {
  p <- ggplot(data,aes_base)+geom_violin(aes(fill=if(!is.null(group)) .data[[group]] else NULL),alpha=.35)+geom_boxplot(width=.14,outlier.shape=NA)+geom_jitter(width=.08,alpha=.4,size=1)
} else if(chart=='beeswarm') {
  p <- ggplot(data,aes_base)+geom_jitter(width=.12,alpha=.6)
} else if(chart %in% c('heatmap','contour','density2d')) {
  value <- if(!is.null(enc$value)) enc$value else enc$color
  p <- ggplot(data,aes_base)
  if(chart=='heatmap') p <- p+geom_tile(aes(fill=.data[[value]]))
  else if(!is.null(value)) p <- p+geom_contour_filled(aes(z=.data[[value]])) else p <- p+stat_density_2d_filled()
} else if(chart %in% c('correlation','clusteredHeatmap')) {
  numeric <- data[vapply(data,is.numeric,logical(1))]; matrix <- cor(numeric,use='pairwise.complete.obs'); melted <- as.data.frame(as.table(matrix)); p <- ggplot(melted,aes(Var1,Var2,fill=Freq))+geom_tile()+geom_text(aes(label=sprintf('%.2f',Freq)),size=2.5)+scale_fill_gradient2(limits=c(-1,1))
} else if(chart %in% c('sankey','alluvial')) {
  suppressPackageStartupMessages(library(ggalluvial)); p <- ggplot(data,aes(axis1=.data[[enc$source]],axis2=.data[[enc$target]],y=if(!is.null(enc$value)) .data[[enc$value]] else 1))+geom_alluvium(aes(fill=.data[[enc$source]]),alpha=.55)+geom_stratum()+geom_text(stat='stratum',aes(label=after_stat(stratum)))
} else if(chart=='survival') {
  p <- ggplot(data,aes_base)+geom_step(aes(color=if(!is.null(group)) .data[[group]] else NULL))
} else if(chart=='forest') {
  p <- ggplot(data,aes_base)+geom_errorbarh(aes(xmin=.data[[enc$errorLower]],xmax=.data[[enc$errorUpper]]),height=.15)+geom_point()+geom_vline(xintercept=0,linewidth=.3)
} else if(chart=='volcano') {
  data$neglogp <- -log10(pmax(data[[y]],.Machine$double.xmin)); data$significant <- data[[y]]<.05 & abs(data[[x]])>=1; p <- ggplot(data,aes(x=.data[[x]],y=neglogp,color=significant))+geom_point(alpha=.65)
} else if(chart=='radar') {
  stop('R radar preview requires an explicit radar extension and is disabled in this controlled template.')
} else if(chart %in% c('scatter3d','surface3d')) {
  suppressPackageStartupMessages(library(plotly)); z <- if(!is.null(enc$value)) enc$value else if(!is.null(enc$size)) enc$size else enc$color
  widget <- plot_ly(data,x=~.data[[x]],y=~.data[[y]],z=~.data[[z]],type=if(chart=='surface3d') 'mesh3d' else 'scatter3d',mode='markers'); htmlwidgets::saveWidget(widget,'output/preview.html',selfcontained=TRUE); p <- NULL
} else {
  stop(paste('Unsupported controlled chart type:',chart))
}
if(!is.null(p)) {
  xa <- axis_by_id('x'); ya <- axis_by_id('y')
  if(!is.null(x)&&is.numeric(data[[x]])) { if(identical(xa$scale,'log')) p<-p+scale_x_log10(limits=axis_limits(xa),breaks=axis_breaks(xa),labels=axis_labels(xa),position=if(identical(xa$position,'secondary')) 'top' else 'bottom') else if(isTRUE(xa$reverse)) p<-p+scale_x_reverse(limits=axis_limits(xa),breaks=axis_breaks(xa),labels=axis_labels(xa),position=if(identical(xa$position,'secondary')) 'top' else 'bottom') else p<-p+scale_x_continuous(limits=axis_limits(xa),breaks=axis_breaks(xa),labels=axis_labels(xa),position=if(identical(xa$position,'secondary')) 'top' else 'bottom') }
  if(!is.null(y)&&is.numeric(data[[y]])) { if(identical(ya$scale,'log')) p<-p+scale_y_log10(limits=axis_limits(ya),breaks=axis_breaks(ya),labels=axis_labels(ya),position=if(identical(ya$position,'secondary')) 'right' else 'left') else if(isTRUE(ya$reverse)) p<-p+scale_y_reverse(limits=axis_limits(ya),breaks=axis_breaks(ya),labels=axis_labels(ya),position=if(identical(ya$position,'secondary')) 'right' else 'left') else p<-p+scale_y_continuous(limits=axis_limits(ya),breaks=axis_breaks(ya),labels=axis_labels(ya),position=if(identical(ya$position,'secondary')) 'right' else 'left') }
  p <- p+labs(title=or_default(spec$chart$title,spec$title),subtitle=spec$chart$subtitle,x=or_default(xa$label,x),y=or_default(ya$label,y))+theme_minimal(base_family=strsplit(spec$theme$fontFamily,',')[[1]][1],base_size=spec$theme$baseFontSize)+scale_color_manual(values=unlist(spec$theme$palette))+scale_fill_manual(values=unlist(spec$theme$palette))
  p <- p+theme(axis.text.x=if(isFALSE(xa$showLabels)||isFALSE(xa$visible)) element_blank() else element_text(angle=or_default(xa$labelRotation,0),size=or_default(xa$labelFontSize,spec$theme$baseFontSize),color=or_default(xa$labelColor,'#526172'),hjust=if(or_default(xa$labelRotation,0)!=0) 1 else .5),axis.text.y=if(isFALSE(ya$showLabels)||isFALSE(ya$visible)) element_blank() else element_text(angle=or_default(ya$labelRotation,0),size=or_default(ya$labelFontSize,spec$theme$baseFontSize),color=or_default(ya$labelColor,'#526172')),axis.title.x=if(isFALSE(xa$visible)) element_blank() else element_text(size=or_default(xa$titleFontSize,spec$theme$baseFontSize),color=or_default(xa$titleColor,'#26364a'),margin=margin(t=or_default(xa$titleGap,8))),axis.title.y=if(isFALSE(ya$visible)) element_blank() else element_text(size=or_default(ya$titleFontSize,spec$theme$baseFontSize),color=or_default(ya$titleColor,'#26364a'),margin=margin(r=or_default(ya$titleGap,8))),axis.ticks.x=if(isFALSE(xa$showTicks)||isFALSE(xa$visible)) element_blank() else element_line(),axis.ticks.y=if(isFALSE(ya$showTicks)||isFALSE(ya$visible)) element_blank() else element_line(),axis.line.x=if(isFALSE(xa$showLine)||isFALSE(xa$visible)) element_blank() else element_line(),axis.line.y=if(isFALSE(ya$showLine)||isFALSE(ya$visible)) element_blank() else element_line(),panel.grid.major.x=if(isFALSE(xa$showGrid)) element_blank() else element_line(color=or_default(xa$gridColor,'#e4e8ed'),linewidth=or_default(xa$gridWidth,.8)),panel.grid.major.y=if(isFALSE(ya$showGrid)) element_blank() else element_line(color=or_default(ya$gridColor,'#e4e8ed'),linewidth=or_default(ya$gridWidth,.8)),panel.grid.minor.x=if(isTRUE(xa$showMinorGrid)) element_line(color=or_default(xa$gridColor,'#eef1f4'),linewidth=or_default(xa$gridWidth,.8)*.6) else element_blank(),panel.grid.minor.y=if(isTRUE(ya$showMinorGrid)) element_line(color=or_default(ya$gridColor,'#eef1f4'),linewidth=or_default(ya$gridWidth,.8)*.6) else element_blank())
  ggsave('output/preview.svg',p,width=spec$theme$canvas$widthMm/25.4,height=spec$theme$canvas$heightMm/25.4,device=svglite::svglite)
  ggsave('output/preview.png',p,width=spec$theme$canvas$widthMm/25.4,height=spec$theme$canvas$heightMm/25.4,dpi=180)
  preview <- 'preview.svg'
  for(item in spec$exports){ fmt<-item$format; if(fmt %in% c('png','svg','pdf','tiff')) ggsave(file.path('output',paste0('export-',item$id,'.',fmt)),p,dpi=ifelse(is.null(item$dpi),300,item$dpi),device=fmt) }
} else preview <- 'preview.html'
results <- list()
for(a in spec$analysis){ if(isFALSE(a$enabled)) next; values<-as.numeric(data[[a$valueField]]); values<-values[is.finite(values)]; item<-list(analysisId=a$id,method=a$type,engine='R/stats',n=length(values)); if(a$type=='descriptive'&&length(values)>1){item$mean<-mean(values);item$sd<-sd(values)}; results[[length(results)+1]]<-item }
write_json(results,'output/analysis-results.json',pretty=TRUE,auto_unbox=TRUE)
write_json(list(language='r',chartType=chart,preview=preview,versions=list(R=R.version.string,ggplot2=as.character(packageVersion('ggplot2')))),'output/render-manifest.json',pretty=TRUE,auto_unbox=TRUE)
`;

const MATLAB_SCRIPT = String.raw`% Generated by FTranslate Scientific Plotting Studio.
spec = jsondecode(fileread('plot-spec.json'));
data = readtable('data.csv','VariableNamingRule','preserve');
if ~exist('output','dir'), mkdir('output'); end
chart = string(spec.chart.type); enc = spec.encodings;
fig = figure('Visible','off','Color','white'); ax = axes(fig); hold(ax,'on');
x = ''; y = ''; if isfield(enc,'x'), x=string(enc.x); end; if isfield(enc,'y'), y=string(enc.y); end
if any(chart == ["line","area","scatter","bar"])
    xv=data.(x); yv=data.(y); if chart=="line", plot(ax,xv,yv,'-o'); elseif chart=="area", area(ax,xv,yv); elseif chart=="scatter", scatter(ax,xv,yv); else, bar(ax,xv,yv); end
elseif chart=="histogram", histogram(ax,data.(x));
elseif chart=="density", [f,xi]=ksdensity(data.(x)); plot(ax,xi,f);
elseif chart=="ecdf", [f,xi]=ecdf(data.(x)); stairs(ax,xi,f);
elseif chart=="box", boxchart(ax,categorical(data.(x)),data.(y));
elseif chart=="violin", boxchart(ax,categorical(data.(x)),data.(y)); scatter(ax,categorical(data.(x)),data.(y),10,'filled','MarkerFaceAlpha',.3);
elseif chart=="beeswarm", swarmchart(ax,categorical(data.(x)),data.(y));
elseif chart=="heatmap", close(fig); fig=figure('Visible','off'); heatmap(data,string(enc.y),string(enc.x),'ColorVariable',string(enc.value));
elseif chart=="contour", tri=delaunay(data.(x),data.(y)); trisurf(tri,data.(x),data.(y),data.(string(enc.value)),'EdgeColor','none'); view(2); colorbar;
elseif chart=="density2d", histogram2(ax,data.(x),data.(y),'DisplayStyle','tile','ShowEmptyBins','on'); colorbar;
elseif any(chart == ["correlation","clusteredHeatmap"]), numeric=data(:,vartype('numeric')); imagesc(ax,corr(table2array(numeric),'Rows','pairwise')); colorbar;
elseif chart=="scatter3d", z=string(enc.value); scatter3(ax,data.(x),data.(y),data.(z),20,data.(z),'filled');
elseif chart=="surface3d", z=string(enc.value); tri=delaunay(data.(x),data.(y)); trisurf(ax,tri,data.(x),data.(y),data.(z));
elseif chart=="survival", stairs(ax,data.(x),data.(y));
elseif chart=="forest", low=string(enc.errorLower); high=string(enc.errorUpper); errorbar(ax,data.(x),1:height(data),data.(x)-data.(low),data.(high)-data.(x),'horizontal','o'); set(ax,'YTick',1:height(data),'YTickLabel',string(data.(y)));
elseif chart=="volcano", p=max(data.(y),realmin); scatter(ax,data.(x),-log10(p),12,'filled'); ylabel(ax,'-log10(p)');
elseif chart=="radar", numeric=data(:,vartype('numeric')); polarplot(ax,[table2array(numeric(1,:)),table2array(numeric(1,1))]);
else, error('Unsupported controlled MATLAB chart type: %s',chart); end
if isgraphics(ax), applyAxisSpec(ax,spec,'x'); applyAxisSpec(ax,spec,'y'); title(ax,string(spec.chart.title)); end
exportgraphics(fig,'output/preview.png','Resolution',180); try, exportgraphics(fig,'output/preview.svg','ContentType','vector'); catch, end
manifest=struct('language','matlab','chartType',chart,'preview','preview.png','versions',struct('MATLAB',version)); fid=fopen('output/render-manifest.json','w'); fwrite(fid,jsonencode(manifest,'PrettyPrint',true),'char'); fclose(fid);
results=struct('engine','MATLAB','version',version); fid=fopen('output/analysis-results.json','w'); fwrite(fid,jsonencode(results,'PrettyPrint',true),'char'); fclose(fid); close(fig);

function applyAxisSpec(ax,spec,id)
a=findAxisSpec(spec,id); if isempty(fieldnames(a)), return; end
isX=strcmp(id,'x');
if isfield(a,'scale') && strcmp(string(a.scale),'log'), if isX, ax.XScale='log'; else, ax.YScale='log'; end, end
if isfield(a,'min') || isfield(a,'max')
    limits=ifelseAxis(isX,xlim(ax),ylim(ax)); if isfield(a,'min'), limits(1)=a.min; end; if isfield(a,'max'), limits(2)=a.max; end
    if isX, xlim(ax,limits); else, ylim(ax,limits); end
end
if isfield(a,'reverse') && a.reverse, if isX, ax.XDir='reverse'; else, ax.YDir='reverse'; end, end
if isfield(a,'position') && strcmp(string(a.position),'secondary'), if isX, ax.XAxisLocation='top'; else, ax.YAxisLocation='right'; end, end
if isfield(a,'tickInterval') && a.tickInterval>0
    limits=ifelseAxis(isX,xlim(ax),ylim(ax)); ticks=ceil(limits(1)/a.tickInterval)*a.tickInterval:a.tickInterval:floor(limits(2)/a.tickInterval)*a.tickInterval; if isX, xticks(ax,ticks); else, yticks(ax,ticks); end
elseif isfield(a,'tickCount') && a.tickCount>=2
    limits=ifelseAxis(isX,xlim(ax),ylim(ax)); ticks=linspace(limits(1),limits(2),round(a.tickCount)); if isX, xticks(ax,ticks); else, yticks(ax,ticks); end
end
if isfield(a,'labelRotation'), if isX, xtickangle(ax,a.labelRotation); else, ytickangle(ax,a.labelRotation); end, end
if isfield(a,'labelFontSize'), ax.FontSize=a.labelFontSize; end
if isfield(a,'labelColor'), color=hexColor(a.labelColor); if isX, ax.XColor=color; else, ax.YColor=color; end, end
if isfield(a,'showTicks') && ~a.showTicks, if isX, ax.XTick=[]; else, ax.YTick=[]; end, end
if isfield(a,'showLabels') && ~a.showLabels, if isX, ax.XTickLabel=[]; else, ax.YTickLabel=[]; end, end
if isfield(a,'minorTicks') && a.minorTicks, if isX, ax.XMinorTick='on'; else, ax.YMinorTick='on'; end, end
if isfield(a,'showGrid'), if isX, ax.XGrid=onOff(a.showGrid); else, ax.YGrid=onOff(a.showGrid); end, end
if isfield(a,'showMinorGrid'), if isX, ax.XMinorGrid=onOff(a.showMinorGrid); else, ax.YMinorGrid=onOff(a.showMinorGrid); end, end
if isfield(a,'gridColor'), ax.GridColor=hexColor(a.gridColor); end; if isfield(a,'gridWidth'), ax.LineWidth=a.gridWidth; end
if isfield(a,'numberFormat')
    places=2; if isfield(a,'decimalPlaces'), places=round(a.decimalPlaces); end
    mode=string(a.numberFormat); if mode=="scientific", fmt="%."+places+"e"; elseif mode=="percent", fmt="percentage"; elseif mode=="fixed", fmt="%,."+places+"f"; else, fmt="auto"; end
    if fmt~="auto", if isX, xtickformat(ax,fmt); else, ytickformat(ax,fmt); end, end
end
if isfield(a,'label')
    if isX, h=xlabel(ax,string(a.label)); else, h=ylabel(ax,string(a.label)); end
    if isfield(a,'titleFontSize'), h.FontSize=a.titleFontSize; end; if isfield(a,'titleColor'), h.Color=hexColor(a.titleColor); end
end
if isfield(a,'visible') && ~a.visible, if isX, ax.XAxis.Visible='off'; else, ax.YAxis.Visible='off'; end, end
end
function a=findAxisSpec(spec,id)
a=struct(); if ~isfield(spec,'axes'), return; end
for k=1:numel(spec.axes), if strcmp(string(spec.axes(k).id),id), a=spec.axes(k); return; end, end
end
function value=ifelseAxis(condition,left,right), if condition, value=left; else, value=right; end, end
function value=onOff(flag), if flag, value='on'; else, value='off'; end, end
function rgb=hexColor(value), text=char(value); if startsWith(text,'#')&&numel(text)==7, rgb=[hex2dec(text(2:3)),hex2dec(text(4:5)),hex2dec(text(6:7))]/255; else, rgb=[.3 .35 .4]; end, end
`;
